INSERT INTO `campsites` (`name`, `type`, `options`, `price`, `availability`, `image_url`, `featured`) VALUES
('Site1', 'Tent', '{"firepit": true, "pets_allowed": true}', 30.00, 'Available', 'site1.jpg', 0),
('Site2', 'Tent', '{"shaded": true, "pets_allowed": true}', 35.00, 'Available', 'site2.jpg', 1),
('Site3', 'Tent', '{"firepit": true, "shaded": true}', 32.00, 'Limited', 'site3.jpg', 0),
('Site4', 'Tent', '{"firepit": true}', 34.00, 'Booked', 'site4.jpg', 1),
('Site5', 'Tent', '{"shaded": true}', 28.00, 'Available', 'site5.jpg', 0),
('Site6', 'Tent', '{"pets_allowed": true}', 29.00, 'Available', 'site6.jpg', 1),
('Site7', 'Tent', '{"firepit": true, "shaded": true, "pets_allowed": true}', 31.00, 'Available', 'site7.jpg', 0),
('Cabin1', 'Cabin', '{"bathroom": true, "kitchenette": true}', 120.00, 'Available', 'cabin1.jpg', 1),
('Cabin2', 'Cabin', '{"bathroom": true, "AC": true}', 140.00, 'Available', 'cabin2.jpg', 0),
('Cabin3', 'Cabin', '{"bathroom": true}', 150.00, 'Booked', 'cabin3.jpg', 1),
('Cabin4', 'Cabin', '{"AC": true, "kitchenette": true}', 135.00, 'Available', 'cabin4.jpg', 1),
('Cabin5', 'Cabin', '{"bathroom": true, "AC": true, "kitchenette": true}', 130.00, 'Limited', 'cabin5.jpg', 0),
('Cabin6', 'Cabin', '{"kitchenette": true}', 138.00, 'Available', 'cabin6.jpg', 0),
('Cabin7', 'Cabin', '{"AC": true}', 142.00, 'Booked', 'cabin7.jpg', 1),
('RV1', 'RV', '{"serviced": true}', 45.00, 'Available', 'rv1.jpg', 1),
('RV2', 'RV', '{"serviced": false}', 50.00, 'Limited', 'rv2.jpg', 0),
('RV3', 'RV', '{"serviced": true}', 48.00, 'Available', 'rv3.jpg', 0),
('RV4', 'RV', '{"serviced": false}', 52.00, 'Booked', 'rv4.jpg', 1),
('RV5', 'RV', '{"serviced": true}', 44.00, 'Available', 'rv5.jpg', 0),
('RV6', 'RV', '{"serviced": false}', 46.00, 'Limited', 'rv6.jpg', 1);